export const sentences: string[] = [
  "The quick brown Fox jumps over the lazy Dog and then runs back to its den near the old Forest",
  "She sells Seashells by the Seashore every single Morning while the bright Sun slowly rises above the distant Mountain peaks",
  "How much wood would a Woodchuck chuck if a Woodchuck could chuck Wood all day long in the deep Forest",
  "Peter Piper picked a peck of Pickled Peppers from a large Pepper farm located deep in the Southern countryside Region",
  "To be or not to be that is the Question whether it is Nobler in the mind to suffer Pain",
  "All that Glitters is not Gold and often People mistake shiny things for Treasure without understanding their true lasting Value",
  "The early Bird catches the Worm and those who wake up First tend to get the best Opportunities in Life",
  "A Journey of a thousand Miles begins with a single Step and the Courage to keep moving Forward every Day",
  "Two Roads diverged in a Yellow Wood and I took the one less Traveled by and that made all Difference",
  "In the Beginning there was Nothing and then slowly over Billions of years the Universe began to take its Shape",
  "The Sun sets slowly over the vast Ocean Horizon casting warm Golden light across the Waves as the Day ends",
  "Practice makes Perfect and the more Time you spend Working on a Skill the better you will Become at it",
  "Knowledge is Power and People who Read and seek Wisdom will always have an Advantage over those who do Not",
  "Never give up on your Dreams no matter how Hard the Road seems because Success is always Worth the Effort",
  "The Stars shine Bright on the darkest Nights and they Remind us that Hope is always found within Difficult Times",
  "Every Morning brings new Opportunities to start Fresh Learn something New and make a Positive difference in the World Today",
  "The vast Ocean is incredibly Deep and full of Mysteries that Humans have not yet fully Explored or Understood today",
  "A good Book can take you on Adventures to Places you have never Been and Teach you about the World",
  "Time Flies when you are having Fun but it also Slips away so we must use every single Moment Wisely",
  "The best Way to Predict the Future is to Create it through Hard Work Dedication and having a Clear Vision",
];
